apiVersion: v1
kind: Pod
metadata:
  name: mongodb-ro
spec:
  containers:
  - image: mongo
    name: mongodb-ro
    volumeMounts:
    - mountPath: /data/db
      name: mongodb-ro
  volumes:
  - name: mongodb-ro
    persistentVolumeClaim:
      claimName: mongo-ro-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-ro-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-ro-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mongodb-ro
    fsType: ext4