apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Passw0rd!0
  DB_Password: UGFzc3cwcmQhMAo=
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    ports:
    - containerPort: 3306
    env:
    - name:  MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name:  db-secret
          key:  DB_Password

